using AssignmentManager.Data;
using AssignmentManager.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Serilog.Parsing;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Reflection.Metadata;
using System.Security.Claims;
using System.Threading;

/*
    TeacherController is under /api/teacher and is protected with [Authorize(Roles = "Teacher")].
    I read the teacher’s id from the JWT, then I only allow them to change their own assignments.
    Lists use pagination.
    Create/update use DTOs so the client doesn’t send the full entity.
    When grading, I load the submission with its assignment and check that Assignment.TeacherId matches the current user.
 */

namespace AssignmentManager.Controllers
{
    [Route("api/teacher")]
    [ApiController]
    [Authorize(Roles = "Teacher")]
    /*
    Base URL: /api/teacher
    [ApiController] → automatic model binding / 400 for bad JSON
    Whole controller requires a JWT and role Teacher
     */
    public class TeacherController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public TeacherController(ApplicationDbContext context)
        {
            _context = context;
            /* Constructor injection. ASP.NET creates ApplicationDbContext and gives it here. You use _context to talk to Postgres */
        }

        private Guid GetCurrentUserId()
        {
            return Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
        }
        /*
            JWT has NameIdentifier = user id (set in AuthController).
            ! means “I know this is not null after login.”
            This is how every action knows which teacher is calling.
         */

        // ==================== CLASSES & SUBJECTS (for dropdowns) ====================
        [HttpGet("classes")]
        public async Task<IActionResult> GetClasses()
        {
            var items = await _context.Classes
                .Where(c => c.IsActive)
                .OrderBy(c => c.Name)
                .Select(c => new { c.Id, c.Name, c.Code })
                .ToListAsync();
            /*  Only active rows
                Sorted by name
                Select returns a small anonymous object (not the full entity)
                ToListAsync() runs the SQL
            Note: frontend dropdowns only need id + name. No need to return the whole entity, only fields the UI needs.
            */

            return Ok(items);
        }

        [HttpGet("subjects")]
        public async Task<IActionResult> GetSubjects()
        {
            var items = await _context.Subjects
                .Where(s => s.IsActive)
                .OrderBy(s => s.Name)
                .Select(s => new { s.Id, s.Name, s.Code })
                .ToListAsync();

            return Ok(items);
        }

        // ==================== CREATE ASSIGNMENT ====================
        [HttpPost("assignments")]
        public async Task<IActionResult> CreateAssignment([FromBody] CreateAssignmentDto dto)
        {
            var assignment = new Assignment
            // var assignment = store it in a variable so you can add it to the context.
            // new Assignment = create one object of type Assignment.
            {
                Title = dto.Title,
                Description = dto.Description,
                Deadline = dto.Deadline,
                MaxMarks = dto.MaxMarks,
                IsPublished = dto.IsPublished,
                TeacherId = GetCurrentUserId(),
                // You map DTO → entity. TeacherId comes from the token so a teacher cannot create an assignment as someone else.
                ClassId = dto.ClassId,
                // referes to which class this assignment is for FK to Classes
                SubjectId = dto.SubjectId
                // referes to Which subject this assignment is for. FK to Subjects
            };

            _context.Assignments.Add(assignment);
            //_context = EF Core (postgresql database session).
            // Assignments = the Assignments table / DbSet.
            // Add(...) = “track this as a new row.”

            /*At this moment:
                Nothing is written to Postgres yet
                EF only marks the object as Added in memory
                Think of it as putting the row in a shopping cart.
            */
            await _context.SaveChangesAsync();
            /*
             This is when EF sends INSERT to the database
                SaveChanges = actually write
                Async = don’t block the thread while waiting for Postgres
                await = wait until the insert finishes

            Why async / await? So the thread is not blocked while waiting for the database.
             */
            return Ok(assignment);
            /*Id is generated by Guid.NewGuid() on the model.
            public Guid Id { get; set; } = Guid.NewGuid();
            So the Guid is created in C# before insert (not by the database).
            */
        }

        // ==================== GET MY ASSIGNMENTS ====================
        [HttpGet("assignments")]
        /*
         * This method handles GET.
         * URL: /api/teacher + assignments → /api/teacher/assignments.
         */
        public async Task<IActionResult> GetMyAssignments([FromQuery] PaginationParams pagination)
        // The parameter [FromQuery] PaginationParams pagination: Reads ?pageNumber=1&pageSize=10 from the URL.
        {
            var teacherId = GetCurrentUserId();
            /*
             * Id of the logged-in teacher from the JWT.
             * Used to show only their assignments.
             */
            var query = _context.Assignments // Start a query on the Assignments table. SQL not run yet.
                .Where(a => a.TeacherId == teacherId) // Filter: TeacherId must match the current user. a is one assignment.
                .Include(a => a.Class) // Include so a.Class.Name / a.Subject.Name work
                .Include(a => a.Subject) // Take only this page (e.g. 10 rows)
                .AsQueryable(); // AsQueryable() keeps it as a query (SQL not run yet)

            var totalCount = await query.CountAsync();
            // Total rows before Skip/Take (needed for PagedResult.TotalPages).

            var list = await query
                .OrderByDescending(a => a.CreatedAt) // Newest first. Always sort before paging.
                .Skip((pagination.PageNumber - 1) * pagination.PageSize) // Skip previous pages. Page 1 → skip 0. Page 2, size 10 → skip 10.
                .Take(pagination.PageSize)
                .Select(a => new // Shape the JSON. Avoids sending navigation loops.
                {
                    a.Id,
                    a.Title,
                    a.Description,
                    a.Deadline,
                    a.MaxMarks,
                    a.IsPublished,
                    a.CreatedAt,
                    ClassName = a.Class.Name,
                    SubjectName = a.Subject.Name
                })
                .ToListAsync(); // Run the SELECT and put this page into list.

            var result = new PagedResult<object> // Anonymous types are not a named T, so they cast to object. Works, but a dedicated DTO would be cleaner.
            {
                Items = list.Cast<object>().ToList(), // Convert the list so it matches List<object>.
                PageNumber = pagination.PageNumber,
                PageSize = pagination.PageSize,
                TotalCount = totalCount
                // Last 3 line fills paging metadata. TotalPages, HasPrevious, HasNext are calculated inside PagedResult.
            };

            return Ok(result); // HTTP 200 + JSON.
        }

        // ==================== UPDATE ASSIGNMENT ====================
        [HttpPut("assignments/{id}")]
        /* This action is PUT /api/teacher/assignments/{id}.
         * The teacher updates their own assignment. Fields they omit stay unchanged.
         */
        public async Task<IActionResult> UpdateAssignment(Guid id, [FromBody] UpdateAssignmentDto dto)
        {
            var teacherId = GetCurrentUserId(); // Logged-in teacher’s id from the JWT.

            var assignment = await _context.Assignments
                .FirstOrDefaultAsync(a => a.Id == id && a.TeacherId == teacherId); // Must be their assignment. Otherwise 404 (hides that the id exists).

            /*
             * Find one row where:
             * 1) id matches the URL, and
             * 2) it belongs to this teacher
             * FirstOrDefaultAsync → the row, or null if none.
             * If the assignment exists but is another teacher’s, you still get null (same as “not found”). That is on purpose so you don’t reveal that the id exists.
             */

            if (assignment == null)
                return NotFound("Assignment not found or you don't have permission");
            /*
             * No row (or not yours) → HTTP 404.
             * Method stops here. Nothing is updated.
             */

            assignment.Title = dto.Title ?? assignment.Title; // ?? = if client sent null, keep the old value. That’s why update DTO properties are nullable (string?, int?).
            /*
             * ?? = null-coalescing.
             * If dto.Title is null (client didn’t send a new title), keep the old title.
             * If they sent a string, replace it.
             * That’s why UpdateAssignmentDto.Title is string?.
             */
            assignment.Description = dto.Description ?? assignment.Description;
            assignment.Deadline = dto.Deadline ?? assignment.Deadline;
            assignment.MaxMarks = dto.MaxMarks ?? assignment.MaxMarks;
            assignment.IsPublished = dto.IsPublished ?? assignment.IsPublished;
            /*Same idea for each field. DateTime?, int?, bool? so “not sent” is null, not 0 or false (which could be real values).*/

            if (dto.ClassId.HasValue) assignment.ClassId = dto.ClassId.Value;
            /*
             * ClassId is Guid?.
             * HasValue = client sent a Guid.
             * Then .Value is that Guid.
             * If they omitted classId, don’t touch it.
             * You can’t use ?? the same way as easily with Guid, because default Guid is 0000... which is a real (empty) value. HasValue is the safe check.
             */
            if (dto.SubjectId.HasValue) assignment.SubjectId = dto.SubjectId.Value;
            // Same for subject.

            await _context.SaveChangesAsync();
            /*
             * EF saw you changed tracked properties → sends UPDATE to Postgres.
             * No need to call Update(...) because the entity was already loaded and tracked.
             */
            return Ok(assignment);
        }

        // ==================== DELETE ASSIGNMENT ====================
        /*
         * This action is DELETE /api/teacher/assignments/{id}.
         * The teacher deletes their own assignment.
         */
        [HttpDelete("assignments/{id}")] // Same ownership check, then Remove + SaveChanges.
        /*
         * {id} comes from the URL.
         * Example: DELETE /api/teacher/assignments/3f2504e0-...
         */
        public async Task<IActionResult> DeleteAssignment(Guid id)
        /* async / Task<IActionResult> → wait for DB, then return HTTP result
         * Guid id → bound from {id}
         * No [FromBody] — delete usually needs only the id
         * 
         */
        {
            var teacherId = GetCurrentUserId();
            // Logged-in teacher’s id from the JWT.

            var assignment = await _context.Assignments
                .FirstOrDefaultAsync(a => a.Id == id && a.TeacherId == teacherId);

            if (assignment == null)
                return NotFound("Assignment not found or you don't have permission");
            // Not found or not yours → HTTP 404. Stop. Nothing is deleted.

            _context.Assignments.Remove(assignment); // This is Hard-delete. follow-up or Ask Yourself: you could set a flag (soft delete) instead.
            /*
             * Mark this entity as Deleted in EF’s tracker.
              * Postgres is not changed yet.
              * This is a hard delete: the row will be removed from the table.
              * Soft delete would be assignment.IsPublished = false or an IsDeleted flag instead of Remove.
              * If the assignment has submissions, delete may fail unless cascade is configured (interview follow-up).
             */
            await _context.SaveChangesAsync();
            /*
             * EF sends DELETE FROM ... WHERE "Id" = @id.
             * Now the row is gone.
             */
            return Ok(new { message = "Assignment deleted successfully" });
        }

        // ==================== VIEW SUBMISSIONS ====================
        /*
         * This action is GET /api/teacher/assignments/{assignmentId}/submissions.
         * It lists all submissions for one assignment, only if that assignment belongs to the logged-in teacher.
         */
        [HttpGet("assignments/{assignmentId}/submissions")]
        // This action is PUT /api/teacher/assignments/{id}.
        // The teacher updates their own assignment. Fields they omit stay unchanged.
        public async Task<IActionResult> GetSubmissionsOfAssignment(Guid assignmentId)
        /*
         * async Task<IActionResult> → wait for DB, return HTTP result
         * Guid assignmentId → from {assignmentId}
         * No body; no pagination here (returns the full list)
         */
        {
            var teacherId = GetCurrentUserId(); //Current teacher’s id from the JWT.

            var assignment = await _context.Assignments
                .FirstOrDefaultAsync(a => a.Id == assignmentId && a.TeacherId == teacherId);
            /*
             * Load that assignment only if it is theirs.
             * Wrong id or another teacher’s assignment → null.
             */

            if (assignment == null)
                return NotFound("Assignment not found or you don't have permission");
            // 404 and stop. You never return another teacher’s students’ answers.

            var submissions = await _context.Submissions // Now query the Submissions table.
                .Where(s => s.AssignmentId == assignmentId)
                /*
                 * Only submissions for this assignment.
                 * s = one submission.
                 */
                .Include(s => s.Student)
                // Join the User (student) so s.Student.FullName and Email work.
                .Select(s => new
                {
                    s.Id, // submission id (needed later to grade)
                    StudentName = s.Student.FullName, // who submitted (not the whole User)
                    StudentEmail = s.Student.Email,
                    s.Answer, // Answer: their text
                    s.SubmittedAt, // SubmittedAt: when
                    s.MarksObtained, // null if not graded yet
                    s.Feedback, // teacher comment
                    s.Status // Submitted / Graded / …
                })
                .ToListAsync(); // Run the SQL and put all matching rows in a list.

            return Ok(submissions);
        }

        // ==================== GRADE SUBMISSION ====================
        /* 
         * This action is PUT /api/teacher/submissions/{id}/grade.
         * The teacher sets marks, feedback, and status on one submission, only if that submission belongs to their assignment.
         */
        [HttpPut("submissions/{id}/grade")]
        /*
         * PUT = update.
         * Full URL: /api/teacher/submissions/{id}/grade
         * {id} is the submission id, not the assignment id.
         */
        public async Task<IActionResult> GradeSubmission(Guid id, [FromBody] GradeDto dto)
        /*
         * Guid id: submission id from the URL
         * [FromBody] GradeDto dtoJSON: marks, feedback, optional status
         */
        {
            var teacherId = GetCurrentUserId(); // Logged-in teacher from the JWT.

            var submission = await _context.Submissions
                .Include(s => s.Assignment) // Need Assignment.TeacherId to authorize.
                .FirstOrDefaultAsync(s => s.Id == id);
            /*
             * Load the submission by id.
             * Include loads the related Assignment because you need Assignment.TeacherId to check ownership.
             * Without Include, submission.Assignment would be null and the next check would crash.
             */

            if (submission == null)
                return NotFound("Submission not found");
            // No such submission id → HTTP 404. Stop.

            if (submission.Assignment.TeacherId != teacherId)
                return Forbid("You can only grade submissions of your own assignments");
            /*
             * Submission exists, but its assignment was created by another teacher.
             * HTTP 403 Forbidden (you are logged in, but not allowed).
             * Different from 404: here you admit the submission exists, but deny access
             */

            submission.MarksObtained = dto.Marks;
            /*
             * Save the score.
             * Marks is int (not int?), so the client is expected to send a number.
             */
            submission.Feedback = dto.Feedback;
            // Teacher comment. Can be null.
            submission.Status = dto.Status ?? "Graded";
            /*
             * If the client sent a status, use it.
             * If they sent null / omitted it, default to "Graded".
             */

            await _context.SaveChangesAsync();
            /*
             * EF sends UPDATE (entity was already tracked).
             * Marks, feedback, and status are now in the database.
             */
            return Ok(submission);
        }

        // ==================== CHANGE STATUS ====================
        /*
         * This action is PUT /api/teacher/submissions/{id}/status.
         * The teacher changes only the status of a submission (not marks). It must belong to their assignment.
         */
        [HttpPut("submissions/{id}/status")]
        /*
         * PUT = update.
         * URL: /api/teacher/submissions/{id}/status
         * {id} = submission id.
         */
        public async Task<IActionResult> ChangeSubmissionStatus(Guid id, [FromBody] ChangeStatusDto dto)
        // Guid id: submission id from the URL
        // [FromBody] ChangeStatusDto dto: JSON with new status
        {
            var teacherId = GetCurrentUserId(); // Current teacher’s id from the JWT.

            var submission = await _context.Submissions
                .Include(s => s.Assignment)
                .FirstOrDefaultAsync(s => s.Id == id);
            /*
             * Load that submission.
             * Include loads Assignment so you can check Assignment.TeacherId.
             * No row → null.
             */

            if (submission == null)
                return NotFound("Submission not found");
            // Unknown id → HTTP 404. Stop.

            if (submission.Assignment.TeacherId != teacherId)
                return Forbid("You can only change status of your own assignments' submissions");
            // Submission exists, but the assignment is not yours → HTTP 403.

            submission.Status = dto.Status;
            /*
             * Overwrite status with whatever the client sent (Submitted, Graded, Late, …).
             * No extra check that the string is valid (an enum would be safer).
             */
            await _context.SaveChangesAsync();
            // Write the UPDATE to Postgres.
            return Ok(new { message = "Status updated", status = submission.Status });
            /*
             * HTTP 200.
             * Small JSON, not the whole submission:
             */
        }
    }

    // ==================== DTOs ====================
    /*
     * This is not a database table.
     * It is the JSON shape the teacher sends when creating an assignment (POST /api/teacher/assignments).
     * You copy these fields into a real Assignment entity. You do not let the client send TeacherId or Id.
     */
    public class CreateAssignmentDto
    {
        public string Title { get; set; } = string.Empty;
        /*Required title.
        string (not string?) + default "" so it is never null.
        FluentValidation also says: not empty, max 200 characters.
        */
        public string? Description { get; set; }
        /*Optional description. ? = client may omit it or send null.*/
        public DateTime Deadline { get; set; }
        /*
         * Due date. Required (DateTime, not DateTime?).
         * Validator: must be after DateTime.UtcNow.
         */
        public int MaxMarks { get; set; }
        /*
         * Maximum score. Required.
         * Validator: must be > 0.
         * (0 would be allowed by C# alone; validation blocks it.)
         */
        public bool IsPublished { get; set; } = false;
        /*
         * Draft vs published.
         * Default false = if the client omits it, the assignment is a draft. Students won’t see it until published.
         */
        public Guid ClassId { get; set; }
        /*
         * Which subject. Same idea as ClassId.
         */
        public Guid SubjectId { get; set; }
    }

    public class UpdateAssignmentDto
    {
        public string? Title { get; set; }
        /*
         * Optional new title.
         * null = don’t change title.
         * A string = replace title.
         */
        public string? Description { get; set; }
        /*
         * Optional description.
         * null = keep old description.
         */
        public DateTime? Deadline { get; set; }
        public int? MaxMarks { get; set; }
        public bool? IsPublished { get; set; }
        public Guid? ClassId { get; set; }
        public Guid? SubjectId { get; set; }
    }

    public class GradeDto
    {
        public int Marks { get; set; }
        public string? Feedback { get; set; }
        public string? Status { get; set; } = "Graded";
    }

    public class ChangeStatusDto
    {
        public string Status { get; set; } = string.Empty;
    }

    /*
    
        
    Why not return the entity on GET lists?
        Smaller JSON, no cycles, no extra data.
        Security pattern you used:
        Id from JWT + TeacherId == currentUser on every write.
        
    What you would improve:
        Dedicated response DTOs instead of PagedResult<object>
        Check teacher is assigned to that class+subject before create
        Enum for status
        Soft delete
        Don’t return full Assignment/Submission entities after create/grade (may over-expose)
     */
        }